openapi: 3.0.3
info:
  title: Fit4Cybersecurity API documentation.
  version: 2.1.0
  description: Documentation of the Fit4Cybersecurity API.
  contact:
    email: opensource@nc3.lu
  license:
    name: GNU Affero General Public License version 3
    url: https://www.gnu.org/licenses/agpl-3.0.html
paths:
  /survey/api/v1/recommendation/:
    get:
      operationId: recommendation_retrieve
      description: List all the items.
      tags:
      - recommendation
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          description: No response body
  /survey/api/v1/schema/:
    get:
      operationId: schema_retrieve
      description: |-
        OpenApi3 schema for this API. Format can be selected via content negotiation.

        - YAML: application/vnd.oai.openapi
        - JSON: application/vnd.oai.openapi+json
      parameters:
      - in: query
        name: format
        schema:
          type: string
          enum:
          - json
          - yaml
      - in: query
        name: lang
        schema:
          type: string
          enum:
          - de
          - en
          - fr
      tags:
      - schema
      security:
      - basicAuth: []
      - cookieAuth: []
      - {}
      responses:
        '200':
          content:
            application/vnd.oai.openapi:
              schema:
                type: object
                additionalProperties: {}
            application/yaml:
              schema:
                type: object
                additionalProperties: {}
            application/vnd.oai.openapi+json:
              schema:
                type: object
                additionalProperties: {}
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
  /survey/api/v1/survey_question/:
    get:
      operationId: survey_question_retrieve
      description: List all the items.
      tags:
      - survey_question
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          description: No response body
  /survey/api/v1/survey_question_answer/:
    get:
      operationId: survey_question_answer_retrieve
      description: List all the items.
      tags:
      - survey_question_answer
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          description: No response body
  /survey/api/v1/survey_section/:
    get:
      operationId: survey_section_retrieve
      description: List all the items.
      tags:
      - survey_section
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          description: No response body
  /survey/api/v1/survey_user/:
    get:
      operationId: survey_user_retrieve
      description: Get all the items.
      tags:
      - survey_user
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          description: No response body
  /survey/api/v1/survey_user/{id}/:
    get:
      operationId: survey_user_retrieve_2
      description: Get an item.
      parameters:
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        required: true
      tags:
      - survey_user
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          description: No response body
  /survey/api/v1/survey_user_answer/{id}/:
    get:
      operationId: survey_user_answer_retrieve
      description: Get an item.
      parameters:
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        required: true
      tags:
      - survey_user_answer
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          description: No response body
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
