
services:
  db:
    image: postgres:latest
    hostname: db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    ports:
      - '5532:5432'
    expose:
      - '5532'
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: ./docker/python/Dockerfile
    tty: true
    volumes:
      - .:/csskp:rw
      - /csskp/static/npm_components/
    ports:
      - "8000:8000"
    expose:
      - '8000'
    depends_on:
      - db
    command: "sh ./wait-for-postgres.sh db ${whitelabel}"
