# Generated by Django 2.2.3 on 2019-08-05 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveySummary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='contact_address_number',
            field=models.IntegerField(),
        ),
    ]
