# Generated by Django 4.1.2 on 2022-11-29 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("survey", "1014_alter_surveyuser_user_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Audit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(
                        max_length=128, verbose_name="Product / Service name"
                    ),
                ),
                (
                    "product_ref",
                    models.CharField(
                        max_length=128, verbose_name="Product / Service reference"
                    ),
                ),
                (
                    "certificate_status",
                    models.CharField(
                        choices=[
                            ("RQ", "Requested"),
                            ("VD", "Valid"),
                            ("RK", "Revoked"),
                        ],
                        default="RQ",
                        max_length=2,
                    ),
                ),
                (
                    "certificate_revocation_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "survey_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="survey.surveyuser",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                (
                    "address_street",
                    models.CharField(max_length=128, verbose_name="Street"),
                ),
                (
                    "address_zip_code",
                    models.CharField(max_length=10, verbose_name="ZIP / Postal code"),
                ),
                ("address_city", models.CharField(max_length=64, verbose_name="City")),
                (
                    "address_country",
                    models.CharField(max_length=64, verbose_name="Country"),
                ),
                ("phone", models.CharField(max_length=12)),
                ("email", models.EmailField(max_length=254)),
                (
                    "type",
                    models.CharField(
                        choices=[("AU", "Audit"), ("CU", "Customer")],
                        default="CU",
                        max_length=2,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AuditUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="audit.company"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AuditByUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "audit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="audit.audit"
                    ),
                ),
                (
                    "audit_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="audit.audituser",
                    ),
                ),
            ],
        ),
    ]
