# Generated by Django 2.2.3 on 2019-08-05 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyuser',
            name='current_question',
            field=models.IntegerField(default=0),
        ),
    ]
