# Generated by Django 2.2.6 on 2019-10-10 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendations',
            name='sector',
            field=models.CharField(blank=True, choices=[('gov', 'Government'), ('adm', 'Public Administrations'), ('fin', 'Financial Sector'), ('it', 'Information Technology (IT)')], default=None, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='surveyuser',
            name='e_count',
            field=models.CharField(choices=[('a', '1-5'), ('b', '6-10'), ('c', '10-20'), ('d', '20-50'), ('e', '50-100'), ('f', '100-200'), ('g', '200-500'), ('h', '500-1000'), ('i', '1000-5000'), ('j', '5000+')], default='a', max_length=2),
        ),
        migrations.AlterField(
            model_name='surveyuser',
            name='sector',
            field=models.CharField(choices=[('gov', 'Government'), ('adm', 'Public Administrations'), ('fin', 'Financial Sector'), ('it', 'Information Technology (IT)')], default='gov', max_length=4),
        ),
    ]
