# Generated by Django 2.2.3 on 2019-09-26 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20190912_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyquestionanswer',
            name='uniqueAnswer',
            field=models.BooleanField(default=False),
        ),
    ]
