# Generated by Django 2.2.3 on 2019-08-06 09:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_surveyuser_current_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyuser',
            name='user_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
