# Generated by Django 2.2.3 on 2019-08-08 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_auto_20190806_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyquestion',
            name='qindex',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='qtype',
            field=models.CharField(choices=[('M', 'Multiple Choice'), ('S', 'Single Choice'), ('I', 'Integer Slider')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='surveyquestionanswer',
            name='aindex',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='surveyuser',
            name='sector',
            field=models.CharField(choices=[('gov', 'Government'), ('adm', 'Public Administrations'), ('fin', 'Sinancial Sector'), ('it', 'Information Technology (IT)')], default='gov', max_length=4),
        ),
    ]
