# Generated by Django 2.2.3 on 2019-08-08 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_auto_20190808_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyquestionanswer',
            name='aindex',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='surveyquestionanswer',
            unique_together={('aindex', 'question')},
        ),
    ]
