# Generated by Django 2.2.3 on 2019-10-07 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_auto_20191003_1432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surveyuseranswer',
            old_name='value',
            new_name='uvalue',
        ),
    ]
