# Generated by Django 2.2.3 on 2019-08-08 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_auto_20190808_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyquestion',
            name='qindex',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='surveyquestionanswer',
            name='aindex',
            field=models.IntegerField(),
        ),
    ]
