# Generated by Django 2.2.3 on 2019-08-13 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_surveyuseranswer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyuseranswer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.SurveyUser'),
        ),
    ]
