# Generated by Django 2.2.3 on 2019-09-09 11:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleKey', models.CharField(max_length=32)),
                ('qtype', models.CharField(choices=[('M', 'Multiple Choice'), ('S', 'Single Choice'), ('I', 'Integer Slider')], default='M', max_length=1)),
                ('qindex', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyQuestionAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answerKey', models.CharField(max_length=32)),
                ('aindex', models.IntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.SurveyQuestion')),
                ('uniqueAnswer', models.BooleanField(default=False)),
                ('score', models.IntegerField(default=0)),
            ],
            options={
                'unique_together': {('aindex', 'question')},
            },
        ),
        migrations.CreateModel(
            name='SurveyQuestionServiceCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleKey', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='SurveySection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sectionTitleKey', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField(default=uuid.uuid4)),
                ('sector', models.CharField(choices=[('gov', 'Government'), ('adm', 'Public Administrations'), ('fin', 'Sinancial Sector'), ('it', 'Information Technology (IT)')], default='gov', max_length=4)),
                ('e_count', models.CharField(choices=[(0, '1-5'), (1, '6-10'), (2, '10-20'), (3, '20-50'), (4, '50-100'), (5, '100-200'), (6, '200-500'), (7, '500-1000'), (8, '1000-5000'), (9, '5000+')], default=0, max_length=2)),
                ('chosenLang', models.CharField(choices=[('EN', 'English'), ('FR', 'Français'), ('DE', 'Deutsch')], default='EN', max_length=2)),
                ('current_question', models.IntegerField(default=0)),
                ('survey_done', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TranslationKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=32)),
                ('text', models.TextField()),
                ('lang', models.CharField(choices=[('EN', 'English'), ('FR', 'Français'), ('DE', 'Deutsch')], default='EN', max_length=2)),
                ('ttype', models.CharField(choices=[('Q', ' Question'), ('A', 'Answer'), ('R', 'Recommendation'), ('S', 'Question Section'), ('C', 'Company Service Category')], default='Q', max_length=1)),
            ],
            options={
                'unique_together': {('lang', 'id')},
            },
        ),
        migrations.CreateModel(
            name='SurveyUserAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uvalue', models.IntegerField(default=0)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.SurveyQuestionAnswer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.SurveyUser')),
            ],
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.SurveySection'),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='service_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.SurveyQuestionServiceCategory'),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='maxPoints',
            field=models.IntegerField(default=10),
        ),
        migrations.CreateModel(
            name='Recommendations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textKey', models.CharField(max_length=32)),
                ('min_e_count', models.CharField(choices=[('a', '1-5'), ('b', '6-10'), ('c', '10-20'), ('d', '20-50'), ('e', '50-100'), ('f', '100-200'), ('g', '200-500'), ('h', '500-1000'), ('i', '1000-5000'), ('j', '5000+')], default='a', max_length=2)),
                ('max_e_count', models.CharField(choices=[('a', '1-5'), ('b', '6-10'), ('c', '10-20'), ('d', '20-50'), ('e', '50-100'), ('f', '100-200'), ('g', '200-500'), ('h', '500-1000'), ('i', '1000-5000'), ('j', '5000+')], default='j', max_length=2)),
                ('sector', models.CharField(blank=True, choices=[('gov', 'Government'), ('adm', 'Public Administrations'), ('fin', 'Sinancial Sector'), ('it', 'Information Technology (IT)')], default=None, max_length=4, null=True)),
                ('answerChosen', models.BooleanField(default=False)),
                ('forAnswer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.SurveyQuestionAnswer')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_tel', models.TextField(max_length=32)),
                ('contact_address_street', models.CharField(max_length=128)),
                ('contact_address_city', models.CharField(max_length=64)),
                ('contact_address_country', models.CharField(choices=[('LU', 'Luxembourg'), ('DE', 'Deutschland'), ('BE', 'Belgique'), ('FR', 'France')], max_length=2)),
                ('contact_address_number', models.IntegerField()),
                ('contact_address_postcode', models.CharField(max_length=10)),
                ('notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CompanyService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(choices=[('SME', 'Small to Medium Size Entreprises'), ('BC', 'Big Company'), ('MN', 'Multinationals Coorporations'), ('IND', 'Independent'), ('PRI', 'Private Person')], max_length=3)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.SurveyQuestionServiceCategory')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Company')),
            ],
        ),
    ]
