# Generated by Django 3.2.8 on 2021-10-20 08:56
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("survey", "0005_auto_20210920_1503"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="contact_address_country",
            field=models.CharField(max_length=4),
        ),
    ]
