# Generated by Django 3.2.8 on 2021-10-20 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0999_insertdata_20191011_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='contact_address_country',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='surveyuser',
            name='country_code',
            field=models.CharField(default='LU', max_length=2),
        ),
    ]
