# Generated by Django 3.2 on 2021-10-08 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '1003_auto_20210920_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyuser',
            name='country_code',
            field=models.CharField(default='LU', max_length=2),
        ),
    ]
