# Generated by Django 3.2.9 on 2021-11-18 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '1003_auto_20211118_0848'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TranslationKey',
        ),
    ]
