# Generated by Django 3.2.9 on 2021-12-08 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '1005_auto_20211201_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyuser',
            name='country_code',
        ),
        migrations.RemoveField(
            model_name='surveyuser',
            name='e_count',
        ),
        migrations.RemoveField(
            model_name='surveyuser',
            name='sector',
        )
    ]
