# Generated by Django 3.2.9 on 2021-12-09 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '1006_auto_20211208_1130'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Translation',
        ),
    ]
