# Generated by Django 4.0 on 2022-01-04 13:10

from django.db import migrations, models, connection
import os


def load_data_from_sql(apps, schema_editor):
    file_path = os.path.join(os.path.dirname(__file__), "update_question_type_ss_to_so.sql")
    sql_statement = open(file_path).read()
    with connection.cursor() as c:
        c.execute(sql_statement)


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '1008_surveyquestion_answers_order_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surveyuser',
            old_name='choosen_lang',
            new_name='chosen_lang',
        ),
        migrations.AddField(
            model_name='surveyquestionanswer',
            name='value',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='company',
            name='contact_address_country',
            field=models.CharField(max_length=64),
        ),
        # Update the data in the db.
        migrations.RunPython(load_data_from_sql),
        migrations.AlterField(
            model_name='surveyquestion',
            name='qtype',
            field=models.CharField(choices=[
                ('M', 'Multiple Choice'),
                ('S', 'Single Choice'),
                ('SO', 'Single Option Choice'),
                ('T', 'Free text'),
                ('MT', 'Multiple Choice + Free Text'),
                ('ST', 'Single Choice + Free Text')
            ], default='M', max_length=2),
        ),
    ]
