# Generated by Django 4.0 on 2022-01-11 09:37
import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("survey", "1009_rename_choosen_lang_surveyuser_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="surveyquestion",
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="surveyquestionanswer",
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
