# Generated by Django 4.0 on 2022-01-13 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '1010_alter_surveyquestion_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyuseranswer',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.surveyquestionanswer'),
        ),
    ]
