# Generated by Django 4.0.1 on 2022-01-25 19:46

from django.db import migrations, models, connection
import django.db.models.deletion


def migrate_to_current_question(apps, schema_editor):
    sql = (
        "update survey_surveyuser as u set current_question_id = ("
        + "select id from survey_surveyquestion as q where qindex = u.current_qindex);"
    )
    with connection.cursor() as c:
        c.execute(sql)


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "1012_surveyquestion_tooltip_surveyquestionanswer_tooltip"),
    ]

    operations = [
        migrations.CreateModel(
            name="SurveyUserQuestionSequence",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("branch", models.SmallIntegerField(default=0)),
                ("level", models.SmallIntegerField(default=1)),
                ("index", models.IntegerField(default=1)),
                ("has_been_answered", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="survey.surveyquestion",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="survey.surveyuser",
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "question", "branch")},
            },
        ),
        migrations.CreateModel(
            name="SurveyAnswerQuestionMap",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("branch", models.SmallIntegerField(default=0)),
                ("level", models.SmallIntegerField(default=1)),
                ("order", models.IntegerField()),
                (
                    "answer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="survey.surveyquestionanswer",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="survey.surveyquestion",
                    ),
                ),
            ],
            options={
                "unique_together": {("answer", "question", "branch")},
            },
        ),
        # We need to update the existed records based on current_qindex.
        migrations.AddField(
            model_name="surveyuser",
            name="current_question",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="survey.surveyquestion",
            ),
        ),
        migrations.RunPython(migrate_to_current_question),
        migrations.AlterField(
            model_name="surveyuser",
            name="current_question",
            field=models.ForeignKey(
                blank=False,
                null=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="survey.surveyquestion",
            ),
        ),
        migrations.RemoveField(
            model_name="surveyuser",
            name="current_qindex",
        ),
        migrations.AddField(
            model_name="recommendations",
            name="categories",
            field=models.ManyToManyField(
                blank=True, to="survey.SurveyQuestionServiceCategory"
            ),
        ),
    ]
