# Generated by Django 4.2.6 on 2023-10-13 10:58
import uuid

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "1013_surveyquestion_uuid_alter_surveyuser_chosen_lang_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SurveyQuestionMaxScore",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("max_score", models.IntegerField(default=0)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="survey.surveyquestion",
                    ),
                ),
                (
                    "selected_answer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="survey.surveyquestionanswer",
                    ),
                ),
            ],
            options={
                "unique_together": {("question", "selected_answer")},
            },
        ),
        migrations.CreateModel(
            name="SurveyQuestionAnswerScore",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.IntegerField(default=0)),
                (
                    "answer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answer_scores",
                        to="survey.surveyquestionanswer",
                    ),
                ),
                (
                    "selected_answer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answer_scores_when_selected",
                        to="survey.surveyquestionanswer",
                    ),
                ),
            ],
            options={
                "unique_together": {("answer", "selected_answer")},
            },
        ),
    ]
