# Generated by Django 4.1.7 on 2023-03-02 10:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "1013_surveyquestion_uuid_alter_surveyuser_chosen_lang_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="surveyquestion",
            name="qtype",
            field=models.CharField(
                choices=[
                    ("M", "Multiple Choice"),
                    ("MS", "Multiple Choice Sortable"),
                    ("S", "Single Choice"),
                    ("SO", "Single Option Choice"),
                    ("T", "Free text"),
                    ("MT", "Multiple Choice + Free Text"),
                    ("ST", "Single Choice + Free Text"),
                    ("CL", "Countries list"),
                ],
                default="M",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="surveyuser",
            name="chosen_lang",
            field=models.CharField(
                choices=[("fr", "French")], default="fr", max_length=2
            ),
        ),
        migrations.AlterField(
            model_name="surveyuser",
            name="user_id",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
