# Generated by Django 4.1.2 on 2022-11-29 08:07
import uuid

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("survey", "1013_surveyquestion_uuid_alter_surveyuser_chosen_lang_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="surveyuser",
            name="user_id",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
