# Generated by Django 4.1.7 on 2023-03-09 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "1014_alter_surveyuser_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="surveyuser",
            name="chosen_lang",
            field=models.CharField(
                choices=[("en", "English")], default="en", max_length=2
            ),
        ),
    ]
